### ISSUE TITLE
How to preload all static assets like video/image before rendering in client end?

### ISSUE THREAD

**Issue by rahulmehra0397** [liqvidjs/player#22]
Is there a way to load all the videos/images before rendering in the browser, because currently the player is running while the video is not loaded. Hence, the video is not in sync with the player time.

**Comment by tomByrer** [comment]
Load the assets in a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), `.then` run Liqvidjs?

**Comment by ysulyma** [comment]
You can use `obstructCanPlay`/`obstructCanPlayThrough` on the `<Video>` element, then use the `canPlay`/`canPlayThrough` promise on the player:

```tsx
import {Player, Video, usePlayer} from "liqvid";

function Lesson() {
  return (
    <Player script={script}>
      <LoadingScreen/>
      <Video
        obstructCanPlayThrough
        src="https://www.example.com/video.mp4" start={0}/>
    </Player>
  );
}

function LoadingScreen() {
  const player = usePlayer();
  const [ready, setReady] = useState(false);
  
  useEffect(() => {
    player.canPlayThrough.then(() => setReady(true));
  }, []);

  if (ready) {
    return null;
  } else {
    return (<div className="loading-screen"></div>);
  }
}
```
Then you would style `.loading-screen` to display a loading message/spinner/etc.

These listen to the [`canplay`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event) and [`canplaythrough`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event) events, respectively. This also works for `<Audio>` elements, but there is no analogue for `<img>` elements.

This is currently undocumented, I'll fix that! @tomByrer's solution would also work.

**Comment by rahulmehra0397** [comment]
@ysulyma yes that worked thanks

**Comment by anishg-cn** [comment]
@ysulyma will the obstructCanPlayThrought work in the case where user seeks forward in the video as well?
